# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
env:
  ACCESS_TOKEN_SECRET: secretkey
  DB_NAME: bcuqogtp2sj30tfkzzfg
  DB_USER: ua9l9izkr4usagpx
  DB_HOST: bcuqogtp2sj30tfkzzfg-mysql.services.clever-cloud.com
  DB_PASSWORD: cIfqRRMvARJtUMvlW3O2
  DB_PORT: 3306

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
